### ISSUE TITLE
Controller support has weird bugs

### ISSUE THREAD

**Issue by MaxLebled** [Facepunch/sbox-mazing#24]
The game looks to be playable with controller, but sometimes you just won't move even though there's a path. It seems to affect going left, mostly.

I could only test on Steam Deck, because I don't understand how controller support works on Windows. (got my xbox controller plugged in and everything, but nothing happens)

Are you able to repro any oddities on controller?

**Comment by Metapyziks** [comment]
Just tested this on PC with an xbone controller, I think I'm getting the same problems. Serves me right for only testing on keyboard 🤦
